### ISSUE TITLE
Is it possible to pass txt2img.py script options?

### ISSUE THREAD

**Issue by irrationalforest** [fboulnois/stable-diffusion-docker#1]
Hi there!

Thank you for creating this, it's really nice to have a self-contained, easily deployable and replicable image to work from.
I'm from a network engineering, not software dev, so please excuse me if this is a silly question. :)

I was just wondering if you are using txt2img.py in this, and if so, is there any way to pass txt2img.py script options when running build.sh?
I've tried specifying things like height (--H), width (--W), samples (--n_samples) etc, both inside and outside the single quotes, but it does not seem to have the usual effect.

Kind regards,
Dominic

**Comment by fboulnois** [comment]
Hi Dominic,

`txt2img.py` and the official huggingface model are pretty different, but I was looking at making at least some of the parameters configurable. I hardcoded several parameters earlier because I was focused on getting everything working.

Let me see if I can make some of the options configurable.

**Comment by fboulnois** [comment]
Check out #2 , it implements a major subset of the available `txt2img.py` options!

**Comment by irrationalforest** [comment]
Wow, that was fast!
Thank you for your time and effort, I'm really excited to try this out with the additional options.
I did not realise that there was a significant difference between the official Huggingface implementation and txt2img.py.

In time I would like to use this as a basis for running Stable-Diffusion containers on the game-design workstations at the school I work in. The students would love to explore the possibilities of image generation AI, especially as it may be used to help create ad-hoc art assets quickly and iteratively.

Kind regards,
Dominic
