### ISSUE TITLE
OSError: Unable to load weights from pytorch checkpoint file for (...)

### ISSUE THREAD

**Issue by furmanlukasz** [fboulnois/stable-diffusion-docker#12]
In direct linux machine I get these error: 

`OSError: Unable to load weights from pytorch checkpoint file for '/home/huggingface/.cache/huggingface/diffusers/models--CompVis--stable-diffusion-v1-4/snapshots/48a1bd8a2d86483de1ac27e95e188569b57a494e/unet/diffusion_pytorch_model.bin' at '/home/huggingface/.cache/huggingface/diffusers/models--CompVis--stable-diffusion-v1-4/snapshots/48a1bd8a2d86483de1ac27e95e188569b57a494e/unet/diffusion_pytorch_model.bin'. If you tried to load a PyTorch model from a TF 2.0 checkpoint, please set from_tf=True.`

Looks like this path is broken when building it `/home/huggingface/.cache/huggingface/diffusers/models--CompVis--stable-diffusion-v1-` but I can pind place where to fix it.

**Comment by fboulnois** [comment]
To clarify, are you trying to run the Python code without Docker or the build script?

**Comment by furmanlukasz** [comment]
This is after building docker container when running `./build run "prompt"`

**Comment by fboulnois** [comment]
I reran the commands on a fresh machine and I wasn't able to reproduce this issue. If you clear out the huggingface volume (`docker volume rm huggingface`), are you able to download all the models successfully to fix the issue? Keep in mind this will permanently erase the volume and all its contents.

**Comment by furmanlukasz** [comment]
That did work! Thank you, however right now it seems that docker has no permission to save it in `output` directory `PermissionError: [Errno 13] Permission denied: 'output/horse_on_the_moon___steps_50__scale_7.50__seed_14724727502852850856__n_1.png'`

**Comment by fboulnois** [comment]
Were you able to resolve this issue? Does the `output` folder exist outside the container? If so, which user owns that folder?

**Comment by furmanlukasz** [comment]
I need to add the docker to a new group, then it had permission to write down the file.
