### ISSUE TITLE
CUDA library is a stub, had to remove /usr/local/cuda/lib64/stubs

### ISSUE THREAD

**Issue by aou** [fboulnois/stable-diffusion-docker#13]
Not sure if other people will run into this, but I added

```
RUN rm -rf /usr/local/cuda/lib64/stubs
```

to the Dockerfile (before USER) to have the CUDA drivers loaded in the container.

**Comment by fboulnois** [comment]
It might be worth adding this to the README. Which version of Docker are you using?

**Comment by aou** [comment]
20.10.17, on NixOS. Which honestly I thought was the cause of my problems; nix with python stuff has been tricky. But this one was actually docker related, possibly a bug in tensorflow's latest-gpu image?

**Comment by fboulnois** [comment]
If you try to build the image on an older version of [tensorflow with gpu](https://hub.docker.com/r/tensorflow/tensorflow/tags), do you still get the error? If so I might switch to using specific versions of the images.

**Comment by aou** [comment]
I will give it a try later tonight and get back to you.

**Comment by aou** [comment]
Built on tensorflow:2.9.2-gpu, could run without deleting that dir. However, went back to :latest, and could also run... will need to do a more rigorous test, could be that I've polluted my docker builds and whatnot. Will try to reproduce the issue and get back to you.

**Comment by aou** [comment]
Ok, thoroughly confused now.. getting pretty inconsistent behavior while I try various tags of tensorflow. Sometimes the `/usr/local/cuda` directory exists, in which case `/usr/local/cuda/lib64/stubs` needs to be deleted for CUDA to load, other times `/usr/locall/cuda` doesn't exist at all, in which case CUDA loads properly. Also strangely, rebuilds of the stable-diffusion-docker image seem to work without needing to delete the stubs directory, regardless of which tensorflow tag it's based on.

Altogether baffling, my docker-fu is clearly not strong enough. Given that no one else seems to be having this issue, probably safe to close.

**Comment by fboulnois** [comment]
Closing the issue for now, it can always be reopened.
