### ISSUE TITLE
Run on less than 8 GB vram

### ISSUE THREAD

**Issue by pastukhov** [fboulnois/stable-diffusion-docker#14]
Please describe how to run it on GPU with less than 8 GB VRAM

**Comment by fboulnois** [comment]
There's no absolute way to support GPUs with <8 GB of RAM. There's [a fork of stable-diffusion](https://github.com/basujindal/stable-diffusion) for GPUs with less memory, but not all of those changes have been pushed up to the official Huggingface release.

In the meantime you can try making images smaller than 512x512 using `--W` and `--H`, using `--half` to use smaller floats, and using the recently added `--attention-slicing` to decrease memory usage (but which also decreases speed).

**Comment by pastukhov** [comment]
Thanks!
