### ISSUE TITLE
Error when i run the container 

### ISSUE THREAD

**Issue by lsaudon** [fboulnois/stable-diffusion-docker#19]
When I try to launch the container. I get this error.
```sh
/usr/bin/env: ‘python\r’: No such file or directory
```

**Comment by fboulnois** [comment]
Has a carriage return accidentally been added to `docker-entrypoint.py`? The python script doesn't have any carriage returns:

```sh
$ xxd -l 32 docker-entrypoint.py 
00000000: 2321 2f75 7372 2f62 696e 2f65 6e76 2070  #!/usr/bin/env p
00000010: 7974 686f 6e0a 696d 706f 7274 2061 7267  ython.import arg
```

`0a` is `\n`, which is a regular newline. If you opened this on Windows, it's possible that your editor converted the Unix newlines (`\n`) to Windows newlines (`\r\n`).

**Comment by lsaudon** [comment]
Git auto-convert CRLF.
I reconvert docker-entrypoint.py from CRLF to LF.
Now, I have this error.
![image](https://user-images.githubusercontent.com/25029876/193427755-9b2e6743-d200-435f-8b4d-e5f39d8f3250.png)

**Comment by fboulnois** [comment]
Does your token file also have a Windows newline? It should be a plain text file with your huggingface token.

**Comment by lsaudon** [comment]
Thank you, that was it.
