### ISSUE TITLE
Which model does this use? 

### ISSUE THREAD

**Issue by chrisbward** [fboulnois/stable-diffusion-docker#30]
Hi,

I've just been trying out different tools, grabbed both of the 1.4 checkpoint files - and with my seed, steps, scale, image size.... was not able to reproduce images I've been creating in this docker container!

I went to look in the huggingface docker volume mounted, but can only see a folder "blobs" and no ckpt to pull out to test with?

Thanks!

**Comment by fboulnois** [comment]
Hello,

The checkpoint files are unofficial distributions of the official models, which live at:

1. https://huggingface.co/CompVis/stable-diffusion-v1-4/blob/main/unet/diffusion_pytorch_model.bin
2. https://huggingface.co/runwayml/stable-diffusion-v1-5/blob/main/unet/diffusion_pytorch_model.bin

Over time, multiple revisions of the same model have been released. In the huggingface container, these are stored in the `snapshots` folder under `~/.cache/huggingface/diffusers/{model}/snapshots/{revision}/unet/diffusion_pytorch_model.bin`

As a result, there are no `ckpt`s, as these are not part of the official distribution.

**Comment by chrisbward** [comment]
oh thanks for this! I have to grab them now otherwise I won't be able to replicate with other tools!
