### ISSUE TITLE
Using a locally downloaded model instead of Huggingface CDN model

### ISSUE THREAD

**Issue by kylewetton** [fboulnois/stable-diffusion-docker#33]
Hi, it's my understanding that this uses the model hosted by Huggingface and therefore needs an access token, is it possible to point to a local model (4~GB) and circumvent the access token requirement?

Please feel free to close this once answered, I know questions shouldn't go into the issues section, sorry!

**Comment by fboulnois** [comment]
Feel free to ask questions in the issues section.

It is indeed possible to use a locally downloaded model, see the [Examples](https://github.com/huggingface/diffusers/blob/main/src/diffusers/pipelines/stable_diffusion/README.md#examples) section in the `diffusers` repository. As mentioned in #30 , `ckpt`s aren't part of the official distribution, but I'm not sure whether the `from_pretrained` method can read them directly or not. I think there are [scripts](https://github.com/huggingface/diffusers/tree/main/scripts) to convert between the various formats, however.
