### ISSUE TITLE
nvidia-container-cli: initialization error: load library failed: libnvidia-ml.so.1: cannot open shared object file: no such file or directory: unknown.

### ISSUE THREAD

**Issue by alonedelshtein** [fboulnois/stable-diffusion-docker#35]
First I want to express my appreciation for your contribution to the community, Thank you.

Now for my question.
I forked the repository to add changes to meet my requirements, unfortunately I failed to run the commands provided by the 'build.sh', except './build.sh'.
The error was 'nvidia-container-cli: initialization error: load library failed: libnvidia-ml.so.1: cannot open shared object file: no such file or directory: unknown.'

So,my last try was to clone your original repo and follow the instructions exactly, and without any changes (not even a bit).
I got the same error.

What am I missing or doing wrong? Do I need to install any driver,sdk, or other action needed on the host running the container?

The host is MacBook pro 2019 intel base 16 GB ram 15’ update with the latest os, and using docker desktop latest version.

I will appreciate a lot any suggestion.

Thanks again,
Alon

**Comment by fboulnois** [comment]
Hello, does your MacBook Pro have an Nvidia GPU? If so, what kind is it?

**Comment by alonedelshtein** [comment]
HI,

I have the 2 graphic cards of Type GPU, but I am not sure it is sufficient.

Here are their details:

Intel UHD Graphics 630:

  Chipset Model:	Intel UHD Graphics 630
  Type:	GPU
  Bus:	Built-In
  VRAM (Dynamic, Max):	1536 MB
  Vendor:	Intel
  Device ID:	0x3e9b
  Revision ID:	0x0000
  Automatic Graphics Switching:	Supported
  gMux Version:	5.0.0
  Metal Support:	Metal 3

Radeon Pro 555X:

  Chipset Model:	Radeon Pro 555X
  Type:	GPU
  Bus:	PCIe
  PCIe Lane Width:	x8
  VRAM (Total):	4 GB
  Vendor:	AMD (0x1002)
  Device ID:	0x67ef
  Revision ID:	0x00e3
  ROM Revision:	113-C980AL-075
  VBIOS Version:	113-C97501P-005
  EFI Driver Version:	01.A1.075
  Automatic Graphics Switching:	Supported
  gMux Version:	5.0.0
  Metal Support:	Metal 2
  Displays:
Color LCD:
  Display Type:	Built-In Retina LCD
  Resolution:	2880 x 1800 Retina
  Framebuffer Depth:	24-Bit Color (ARGB8888)
  Main Display:	Yes
  Mirror:	Off
  Online:	Yes
  Automatically Adjust Brightness:	Yes
  Connection Type:	Internal
DELL P2722HE:
  Resolution:	1920 x 1080 (1080p FHD - Full High Definition)
  UI Looks like:	1920 x 1080 @ 60.00Hz
  Framebuffer Depth:	30-Bit Color (ARGB2101010)
  Display Serial Number:	30WHYG3     
  Mirror:	Off
  Online:	Yes
  Rotation:	Supported
  Connection Type:	Thunderbolt/DisplayPort
VG259:
  Resolution:	1080 x 1920
  UI Looks like:	1080 x 1920 @ 60.00Hz
  Framebuffer Depth:	30-Bit Color (ARGB2101010)
  Display Serial Number:	LALMQS237733
  Mirror:	Off
  Online:	Yes
  Rotation:	270
  Adapter Type:	DVI or HDMI
  Adapter Firmware Version:	ff.c1


What do you think?

**Comment by alonedelshtein** [comment]
I think the issue is that CUDA requires a NVIDIA GPU. AMD/Intel won’t work.
I will try update the driver and comment the results. (Although I doubt it is possible with out writing dedicated driver)

**Comment by fboulnois** [comment]
For systems lacking a suitable GPU, I've added the `--device cpu` option. This should enable the pipeline to work on your Macbook Pro!

**Comment by alonedelshtein** [comment]
Indeed it works with **--device cpu** as you said.
Thanks a lot [fboulnois](https://github.com/fboulnois)!!!
