### ISSUE TITLE
How to run container on a MacBook Pro?

### ISSUE THREAD

**Issue by wellsjo** [fboulnois/stable-diffusion-docker#37]
I always get the following output, even using `--device cpu`. 

```
./build.sh run 'An impressionist painting of a parakeet eating spaghetti in the desert' --device cpu

docker: Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error running hook #0: error running hook: exit status 1, stdout: , stderr: Auto-detected mode as 'legacy'
nvidia-container-cli: initialization error: load library failed: libnvidia-ml.so.1: cannot open shared object file: no such file or directory: unknown.
```

**Comment by fboulnois** [comment]
Is this a Macbook Pro M1 or M2? If you remove `--gpus=all` from the run command in [build.sh](https://github.com/fboulnois/stable-diffusion-docker/blob/main/build.sh#L24), does it work?

**Comment by wellsjo** [comment]
It's a MacBook Pro 2019 `2.8 GHz Quad-Core Intel Core i7, Intel HD Graphics 630 1536 MB`
I removed `--gpus=all` and got a different error this time:
```❯ ./build.sh run 'An impressionist painting of a parakeet eating spaghetti in the desert'
Traceback (most recent call last):
  File "/usr/local/bin/docker-entrypoint.py", line 238, in <module>
    main()
  File "/usr/local/bin/docker-entrypoint.py", line 233, in main
    pipeline = stable_diffusion_pipeline(args)
  File "/usr/local/bin/docker-entrypoint.py", line 66, in stable_diffusion_pipeline
    p.generator = torch.Generator(device=p.device).manual_seed(p.seed)
RuntimeError: CUDA error: CUDA driver version is insufficient for CUDA runtime version
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.```

**Comment by wellsjo** [comment]
okay trying again without `--gpus=all` and with `--device=cpu`, I now get a model access error, which is on my end

```
Access to model CompVis/stable-diffusion-v1-4 is restricted and you are not in the authorized list. Visit https://huggingface.co/CompVis/stable-diffusion-v1-4 to ask for access.
```

**Comment by fboulnois** [comment]
Thank you for the details. It seems that when `--gpus=all` is set Docker tries to do some feature detection before actually launching the container, which complicates using `--device=cpu`. I need to think a little bit on how this could be resolved.

**Comment by wellsjo** [comment]
glad I could help shed some light on the issue :)

**Comment by wellsjo** [comment]
@fboulnois it seems I am getting closer here.

```
❯ ./build.sh run 'An impressionist painting of a rottweiler eating spaghetti in the desert' --device=cpu
load pipeline start: 2022-11-22T17:27:40.423065
Fetching 13 files: 100%|██████████| 13/13 [00:00<00:00, 2021.35it/s]
ftfy or spacy is not installed using BERT BasicTokenizer instead of ftfy.
loaded models after: 2022-11-22T17:28:36.792372
  0%|          | 0/51 [00:00<?, ?it/s]
```

this seems to run okay, but I am not getting any output image

**Comment by fboulnois** [comment]
Is the container running or is it being terminated? When using `--device cpu`, it can take a really long time for it to iterate. If the pipeline ran successfully, you would see a `pipeline completed <time>` message.

**Comment by wellsjo** [comment]
the only output I see is
```
❯ load pipeline start: 2022-11-22T17:44:01.341303
Fetching 13 files: 100%|██████████| 13/13 [00:00<00:00, 1985.51it/s]
ftfy or spacy is not installed using BERT BasicTokenizer instead of ftfy.
loaded models after: 2022-11-22T17:44:56.997787
  0%|          | 0/51 [00:00<?, ?it/s]
```

and then the container gets destroyed

**Comment by fboulnois** [comment]
Docker is probably killing it because it's asking for too many resources (RAM / CPU). You might want to play with adding some of these options to the `docker run` command in the build script: https://docs.docker.com/config/containers/resource_constraints/

**Comment by wellsjo** [comment]
I got it to work by giving more resources to docker through the docker app. thank you!

**Comment by fboulnois** [comment]
Is there a summary of what you did that could be added to the README?

**Comment by fboulnois** [comment]
I fixed the first issue you had with Docker in #38 , please let me know if there is a summary of the steps you took to give Docker more resources that I can add to the README. This would be of great benefit to other users.

**Comment by wellsjo** [comment]
in total it was removing `--gpus=all` from `build.sh`, and then maxing out the docker resources:
Docker preferences -> Resources
maxed out 8 CPUs, 16GB memory, 4GB swap

then it worked

**Comment by fboulnois** [comment]
I added some details for the second issue in the README. Thanks!
