### ISSUE TITLE
CUDA out of memory error

### ISSUE THREAD

**Issue by wellsjo** [fboulnois/stable-diffusion-docker#43]
I'm using a `g5.xlarge` in AWS (and trying with RTX 4090 locally). text-to-image works while image-to-image fails with:

>torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 5.78 GiB (GPU 0; 22.06 GiB total capacity; 19.90 GiB already allocated; 904.38 MiB free; 19.92 GiB reserved in total by PyTorch)

any help would be appreciated! 😄

**Comment by fboulnois** [comment]
What is the size of the image that you're using? Have you tried the options `--attention-slicing` or `--half` to decrease memory use?

**Comment by neoOpus** [comment]
Restarts most of the time solve this sort of issue.
