### ISSUE TITLE
All prompts return "Potential NSFW content was detected in one or more images."

### ISSUE THREAD

**Issue by mayur7garg** [fboulnois/stable-diffusion-docker#5]
### Setup
- OS: Windows 11
- RAM: 16 GB
- Dedicated GPU: 4GB NVIDIA GeForce GTX 1650

### Run command used
.\build.sh run 'magical castle' --W 256 --H 256 --half --seed 42

### Output Generated
- The image generated is fully black.
- In the output of the terminal/container log, this is the error mentioned:

*Potential NSFW content was detected in one or more images. A black image will be returned instead. Try again with a different prompt and/or seed.*

### [container log.txt](https://github.com/fboulnois/stable-diffusion-docker/files/9447525/container.log.txt)

I am using 256*256 resolution with *half* set since my GPU only has 4GB VRAM.
I have tried multiple prompts, including the one used in **README.md** of this project, but all prompts give the same issue. I have tried playing with the seed value too but no change.

**Comment by fboulnois** [comment]
I am not able to reproduce this issue on my Windows box with the command you specified. My guess is there is some combination of hardware / software setup that is causing the issue.

If you run `build.sh dev`, it should drop you into a container. At the terminal, what is the output of these two commands?

```sh
nvidia-smi
python3 -c "import tensorflow as tf; print(tf.config.list_physical_devices('GPU'))"
```

**Comment by mayur7garg** [comment]
I use Docker Desktop on Windows 11 with WSL2 as backend.
I tried with even lower sizes as well but no change. I even tried directly running the container via PS instead of using the shell script but still no change.
Do note that the pipeline is always loaded as per the output. It also goes through all the 50 iterations and an output file is saved too. My GPU usage also reaches almost 100% while the pipeline is running. The output image just happens to be entirely black with the NSFW message in the container output.

I tried running the commands you said in the dev mode. I have attached the outputs and they are in line with what is expected.
[nvidia.txt](https://github.com/fboulnois/stable-diffusion-docker/files/9456028/nvidia.txt)
[tfgpu.txt](https://github.com/fboulnois/stable-diffusion-docker/files/9456030/tfgpu.txt)

**Comment by fboulnois** [comment]
Thank you for including the outputs, I think they eliminate two potential sources of randomness:

- You're using the latest version of the CUDA driver, so version differences between drivers is likely not causing the issue
- The pipeline is able to detect and run on the GPU, so final inference is likely not occurring on the CPU

The Huggingface model has a built-in safety checker: https://github.com/huggingface/diffusers/blob/main/src/diffusers/pipelines/stable_diffusion/safety_checker.py#L76

If you're familiar with Python debugging, I would check why the cosine distance difference is returning > 0 (which flags the image as nsfw).

**Comment by mayur7garg** [comment]
Cool. I will try it over the weekend. Will also try creating a container and a pipeline script myself to see if I can get it working that way.

**Comment by fboulnois** [comment]
I added a few options in the past two weeks, if you try the following does it work?

```sh
build.sh run --W 256 --H 256 --half --skip --attention-slicing --seed 42 --prompt 'magical castle'
```

`--skip` skips the safety checker altogether, and `--attention-slicing` decreases the amount of VRAM used.
