### ISSUE TITLE
I am having trouble with ./build.sh build

### ISSUE THREAD

**Issue by azher-alnabi** [fboulnois/stable-diffusion-docker#57]
Hello!

I am having trouble with line 23 in the file, "Dockerfile" where the following command is this:
Line 23: COPY token.txt /home/huggingface

When I try to:
./build.sh build

I get the following error on Step 11/12" COPY token.txt /home/huggingface":
COPY failed: file not found in build context or excluded by .dockerignore: stat token.txt: file does not exist

I have tried the following:
1. "docker system prune" before building
2.  Added the following to line 21: && touch /home/huggingface/token.txt
3.  Looked at the following stackoverflow link: https://stackoverflow.com/questions/69852628/docker-copy-failed-file-not-found-in-build-context-dockerfile
4. Look at the following youtube link: https://www.youtube.com/watch?v=tXnDA23lvE4
5. Look at other resources

I feel like I made a mistake somewhere that I cannot figure out how to fix. #

**Comment by fboulnois** [comment]
Where is your user access token saved? https://github.com/fboulnois/stable-diffusion-docker#huggingface-token

**Comment by azher-alnabi** [comment]
I wasn't sure where to place my token, would I place it in my .gitignore file where token.txt is, and make token.txt=hf_*****, I apologize for it being a newbie question.

**Comment by fboulnois** [comment]
No, you shouldn't change the `.gitignore` file. Instead, you should create a file called `token.txt` in the project directory, and the contents of the file should be the `hf_...` token.

Alternately, if you download the container using the [quickstart guide](https://github.com/fboulnois/stable-diffusion-docker#quickstart) then all you need to do is pass the option `--token hf_...` when using `./build run`. See the quickstart instructions for more details.

**Comment by azher-alnabi** [comment]
Got it! Thank you very much!
