### ISSUE TITLE
Addition of Samplers

### ISSUE THREAD

**Issue by azher-alnabi** [fboulnois/stable-diffusion-docker#58]
Hello!

I was curious if there would be an addition to change what samplers you would be able to use at ./build.sh run. I am particularly interested in adding the following sampler: (DPM++ 2S a Karras). The reason why I ask is so that I could minimize the step count while maintaining a high-fidelity image as this would allow for a quicker rendering of these images.

Thank you for this docker file!

**Comment by fboulnois** [comment]
Hello! This is already implemented in the underlying `diffusers` library as `DPMSolverSinglestepScheduler`: https://github.com/huggingface/diffusers/issues/277#issuecomment-1371428672 . More information on that scheduler can be found here: https://huggingface.co/docs/diffusers/api/schedulers/singlestep_dpm_solver

You'll want to use the option `--scheduler DPMSolverSinglestepScheduler` with `./build run`.

**Comment by azher-alnabi** [comment]
Works solid, thank you!
