### ISSUE TITLE
Switching Checkpoints

### ISSUE THREAD

**Issue by azher-alnabi** [fboulnois/stable-diffusion-docker#61]
Hello!

I was playing around with trying to switch the checkpoint file, and the method I was using was the following:
./build.sh run --model "andite/anything-v4.0" "andromeda galaxy in a bottle".
However, there was no success in doing so.

Is there a command with which I can implement the following checkpoint file: "https://huggingface.co/andite/anything-v4.0/blob/main/anything-v4.0-pruned-fp16.ckpt"?

I took a look at the following resources prior to this:
Issue 30: https://github.com/fboulnois/stable-diffusion-docker/issues/30
Issue 33: https://github.com/fboulnois/stable-diffusion-docker/issues/33
Scripts: https://github.com/huggingface/diffusers/blob/main/scripts/convert_original_stable_diffusion_to_diffusers.py

**Comment by fboulnois** [comment]
Hello, this functionality isn't supported. If you create a pull request to add this functionality I'll consider it though!

**Comment by azher-alnabi** [comment]
Okay, sounds good. Thank you 👍
