### ISSUE TITLE
PermissionError: [Errno 13] Permission denied: '/output/(name).png'

### ISSUE THREAD

**Issue by TheBread1** [fboulnois/stable-diffusion-docker#67]
Just reinstalled Debian and set stable diffusion up, and I've never gotten this error before. Any thoughts that could help? Doing everything properly, running build.sh in sudo

**Comment by fboulnois** [comment]
Does the fix from https://github.com/fboulnois/stable-diffusion-docker/issues/12#issuecomment-1252032291 work?

**Comment by TheBread1** [comment]
Him purging the huggingface thing or changing docker to a new group?

**Comment by TheBread1** [comment]
I managed to fix it. the output folder was owned by root, I chowned it to my user and that fixed it
