### ISSUE TITLE
When using txt2img, I get the error "AttributeError: 'NoneType' object has no attribute 'replace'".

### ISSUE THREAD

**Issue by TheBread1** [fboulnois/stable-diffusion-docker#69]
Pretty much the title. Can anyone help me?
![image](https://user-images.githubusercontent.com/89608969/218355246-70638170-d011-4300-91c2-6c5ceb78ebf4.png)

**Comment by fboulnois** [comment]
Can you post your command line arguments?

**Comment by TheBread1** [comment]
> Can you post your command line arguments?

sudo ./build.sh run --image Untitled.png --negative-prompt "bike" --device cpu

**Comment by fboulnois** [comment]
Make sure you include a positive prompt using `--prompt` .

**Comment by TheBread1** [comment]
> Make sure you include a positive prompt using `--prompt` .

that worked, thank you! I am such an idiot
