### ISSUE TITLE
non display after a completed pipeline

### ISSUE THREAD

**Issue by khalilxg** [fboulnois/stable-diffusion-docker#89]
this is my terminal, after install all requirements and testing first command, i get no response, no image displayed. thanks.

"""
(stable) ubuntu@ubuntuu:~/Downloads/stable-diffusion-docker-main$ ./build.sh run 'Andromeda galaxy in a bottle' --device cpu --onnx
load pipeline start: 2023-08-07T00:11:30.714407
loaded models after: 2023-08-07T00:11:41.887265
100%|██████████| 51/51 [03:23<00:00,  3.99s/it]
completed pipeline: 2023-08-07T00:15:12.201066
"""

**Comment by fboulnois** [comment]
Have you looked in the [output folder](https://github.com/fboulnois/stable-diffusion-docker#outputs) for your image?
