### ISSUE TITLE
change download-location to other drive

### ISSUE THREAD

**Issue by zamweis** [fboulnois/stable-diffusion-docker#91]
Hi
first of all, great work. I love it.
I would like to change the default download-location to another drive, because I'm running out of storage space.
So far I was unable to change the location. Any help would be great

**Comment by fboulnois** [comment]
You need to change [this line](https://github.com/fboulnois/stable-diffusion-docker/blob/main/build.sh#L45) from `"$PWD"/output` to another location.

**Comment by zamweis** [comment]
I had a little mistake in the line and couldn't find the new download
location.
Thanks anyway :)
Cheers
