### ISSUE TITLE
--image command line no longer works

### ISSUE THREAD

**Issue by apekris** [fboulnois/stable-diffusion-docker#99]
After a recent `git pull` running the same command to generate an image from an image no longer works:
```
./build.sh run  --image img.png "<desc>"
```

I do see the log line `loaded image from img.png: 2024-02-01T18:00:40.999099` yet nothing resembling the image ever comes out (like it did before) despite playing with `strength` and `image-scale` options

**Comment by fboulnois** [comment]
I am not able to reproduce this on my end.
